# Generated by Django 5.1.3 on 2024-11-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estudantes', '0002_administrador_dadosacademicos_emocoes_estudante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emocoes',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
