# Generated by Django 5.1.3 on 2024-12-17 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estudantes', '0005_city_uf_address_organization_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'Formato inválido de CEP. Exemplo: 12345-678')]),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
