# Generated by Django 5.1.3 on 2025-01-12 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_estudantes', '0008_alter_student_email_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosacademicos',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_estudantes.student'),
        ),
        migrations.AlterField(
            model_name='relatorios',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_estudantes.student'),
        ),
        migrations.AlterField(
            model_name='emocoes',
            name='matricula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao_estudantes.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Estudante',
        ),
    ]
